FROM ubuntu

# install nginx
RUN apt-get update && apt-get install -y nginx
RUN rm -rf /etc/nginx/sites-enabled/default

# install express js
RUN apt install -y nodejs npm
RUN npm install --prefix /etc/server express --save

# copy config
COPY ./nginx.conf /etc/nginx/nginx.conf
COPY ./.dockpass /etc/nginx/.dockpass

# install certbot
RUN apt install -y python3 python3-venv libaugeas0
RUN python3 -m venv /opt/certbot/
RUN /opt/certbot/bin/pip install --upgrade pip
RUN /opt/certbot/bin/pip install certbot certbot-nginx
RUN ln -s /opt/certbot/bin/certbot /usr/bin/certbot

# copy express folder
COPY ./server.js /etc/server/server.js

COPY ./start.sh /etc/server/start.sh
ENTRYPOINT sh /etc/server/start.sh && nginx -g 'daemon off;' 
