version: '3.7'

networks:
  docknet:
    external: false

services:
  traefik:
    image: traefik:v2.4
    container_name: dockhost
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/traefik.yml:/traefik.yml:ro
      - ./data/configurations:/configurations
    networks:
      - docknet
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=docknet"
      - "traefik.http.routers.dockhost.rule=Host(`gitproject.ch`)"
  whoami:
    image: traefik/whoami
    networks:
      - docknet
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=docknet"
      - "traefik.http.routers.whoami.rule=Host(`gitproject.ch`)"